### ISSUE TITLE
Entire program broken

### ISSUE THREAD

**Issue by jaykm** [msemple1111/kahoot-hack#1]
Check your code.

Please Enter the kahoot pin: 637732
Please Enter the base name: name
Traceback (most recent call last):
  File "flood.py", line 32, in <module>
    pin, name, exc = get_input()
  File "flood.py", line 15, in get_input
    name = input("Please Enter the base name: ")
  File "<string>", line 1, in <module>
NameError: name 'name' is not defined

**Comment by msemple1111** [comment]
@jaykm it is fixed now
