### ISSUE TITLE
connection timed out

### ISSUE THREAD

**Issue by liambagge** [msemple1111/kahoot-hack#22]
root@ubuntu-512mb-fra1-01:/usr/src/kahoot-hack# python3 flood.py
Please Enter the kahoot pin: 961711
Please Enter the base name: base
Please Enter how many names to add: 1000
Traceback (most recent call last):
  File "/usr/src/kahoot-hack/lib/requests/packages/urllib3/connection.py", line 138, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/src/kahoot-hack/lib/requests/packages/urllib3/util/connection.py", line 98, in create_connection
    raise err
  File "/usr/src/kahoot-hack/lib/requests/packages/urllib3/util/connection.py", line 88, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/kahoot-hack/lib/requests/packages/urllib3/connectionpool.py", line 594, in urlopen
    chunked=chunked)
  File "/usr/src/kahoot-hack/lib/requests/packages/urllib3/connectionpool.py", line 350, in _make_request
    self._validate_conn(conn)
  File "/usr/src/kahoot-hack/lib/requests/packages/urllib3/connectionpool.py", line 835, in _validate_conn
    conn.connect()
  File "/usr/src/kahoot-hack/lib/requests/packages/urllib3/connection.py", line 281, in connect
    conn = self._new_conn()
  File "/usr/src/kahoot-hack/lib/requests/packages/urllib3/connection.py", line 147, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
requests.packages.urllib3.exceptions.NewConnectionError: <requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f0b5cd2dd68>: Failed to establish a new connection: [Errno 110] Connection timed out

**Comment by msemple1111** [comment]
After around 75 connections kahoot seems to time out or return weird errors.
This project was designed very quickly and only tested with smaller numbers of users (around 20-40), so it usually doesn't return the correct errors when it times out but it seems to have this time. 

Kahoot itself was also poorly designed for this sort of scale and struggles connecting more than 50 users without lag and has a lot of trouble over 200 - it was designed for the classroom where the size is always reasonably small for it not to cause much of an issue.

**Comment by msemple1111** [comment]
It also depends on your connection bandwidth so I would try and see how many connections you can comfortably take. Start at about 30 users and increase in increments of 30 until you get issues then use a value around there.
